"""AI commit message generation (hybrid mode).

Order in 'hybrid' mode: Ollama (local) -> Gemini (cloud) -> None (the caller uses
the deterministic fallback). Privacy: the diff content is only sent to the cloud
if `cloud_send_content` is True; otherwise, only `--stat` + names.

Uses only the standard library (urllib) to avoid extra dependencies. The commit
is NEVER blocked by the AI: any failure returns None and the fallback is used.
See §6 of DESIGN.md.
"""

import json
import logging
import os
import re
import urllib.error
import urllib.request

log = logging.getLogger("sincrogit.ai")

# A line that looks like a commit subject (Conventional Commits + our sincro:/auto:
# prefixes). Used to pick the real title even when a chatty model adds a preamble.
_SUBJECT_RE = re.compile(
    r"^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert|sincro|auto)"
    r"(\([^)]+\))?!?: ",
    re.IGNORECASE,
)


def generate_commit_message(ai_cfg, diff_stat: str, diff_text: str, manual: bool = False):
    """Return (title, body) or None if it couldn't (=> use fallback).

    `manual=False` -> automatic seal: a neutral 'sincro:' message.
    `manual=True`  -> a developer's manual commit: a Conventional-Commits message
    (feat/fix/...) summarizing the work.
    """
    mode = ai_cfg.mode
    if mode == "none":
        return None

    providers = []
    if mode in ("hybrid", "local"):
        providers.append("ollama")
    if mode in ("hybrid", "cloud"):
        providers.append("cloud")

    for provider in providers:
        try:
            if provider == "ollama":
                text = _call_ollama(ai_cfg, _build_prompt(ai_cfg, diff_stat, diff_text, include_content=True, manual=manual))
            else:
                include = bool(ai_cfg.cloud_send_content)
                text = _call_cloud(ai_cfg, _build_prompt(ai_cfg, diff_stat, diff_text, include_content=include, manual=manual))
            title, body = _split_message(text)
            if title:
                log.info("message generated by AI (%s)", provider)
                return title, body
        except Exception as e:  # noqa: BLE001 — any failure falls through to the next
            # Defense-in-depth: never let the API key reach the log, even if some
            # error string happens to embed it.
            secret = os.environ.get(ai_cfg.api_key_env, "")
            msg = str(e).replace(secret, "***") if secret else str(e)
            log.warning("AI (%s) unavailable: %s", provider, msg)

    return None


# --------------------------------------------------------------------- prompt
def _build_prompt(ai_cfg, diff_stat: str, diff_text: str, include_content: bool, manual: bool = False) -> str:
    lang = "Spanish" if ai_cfg.language == "es" else "English"

    if manual:
        return _build_manual_prompt(lang, diff_stat, diff_text, include_content)

    # Automatic seal: a SincroGit seal is a time-bucket of a whole work session,
    # not a single hand-crafted change, so we don't pretend to classify it as a
    # feat/fix. The neutral 'sincro:' prefix marks it as a machine commit (easy to
    # tell apart from the developer's own commits). See §6 of DESIGN.md.
    body = (
        f"You are an assistant that writes concise git commit messages in {lang}.\n"
        "You are summarizing an AUTOMATIC SNAPSHOT of a work session (unrelated "
        "edits may be mixed together), not a single change.\n"
        "Reply with ONLY the commit message. Rules:\n"
        "- First line: 'sincro: <summary>', at most 72 characters, no trailing period.\n"
        "- Keep the literal 'sincro:' prefix (it marks an automatic commit).\n"
        "- Write the summary in the imperative mood (e.g. 'add X', not 'added X').\n"
    )
    if include_content and diff_text.strip():
        body += (
            "- Optionally add up to 5 '- ' bullets with the most relevant details.\n"
            "Do not add explanations, quotes or code blocks.\n\n"
            "Change summary (git diff --stat):\n"
            f"{diff_stat.strip() or '(no stat)'}\n"
            f"\nDiff:\n{diff_text.strip()}\n"
        )
    else:
        body += (
            "- Optionally add up to 5 '- ' bullets naming the most relevant files.\n"
            "Do not add explanations, quotes or code blocks.\n\n"
            "Change summary (git diff --stat):\n"
            f"{diff_stat.strip() or '(no stat)'}\n"
        )
    return body


def _build_manual_prompt(lang: str, diff_stat: str, diff_text: str, include_content: bool) -> str:
    """Prompt for a developer's MANUAL commit: a Conventional-Commits message that
    summarizes the work. The diff may span changes already captured in earlier
    automatic commits, so we ask for a cumulative summary."""
    body = (
        f"You are an assistant that writes a git commit message in {lang}.\n"
        "This is a developer's MANUAL commit marking a finished unit of work. The "
        "diff below may span work already auto-committed in earlier commits, so "
        "write a concise CUMULATIVE SUMMARY of the overall change.\n"
        "Reply with ONLY the commit message. Rules:\n"
        "- First line: '<type>: <summary>' (Conventional Commits), at most 72 "
        "characters, no trailing period.\n"
        "- <type> is one of: feat, fix, docs, refactor, test, chore.\n"
        "- Do NOT use 'sincro' as the type (it is reserved for automatic commits).\n"
        "- Write the summary in the imperative mood (e.g. 'add X', not 'added X').\n"
        "- Keep <type> in English even if the summary is in another language.\n"
        "- Optionally add up to 5 '- ' bullets with the relevant details.\n"
        "Do not add explanations, quotes or code blocks.\n\n"
        "Change summary (git diff --stat):\n"
        f"{diff_stat.strip() or '(no stat)'}\n"
    )
    if include_content and diff_text.strip():
        body += f"\nDiff:\n{diff_text.strip()}\n"
    return body


def _split_message(text: str):
    if not text:
        return None, ""
    # Drop code-fence marker lines (``` or ```lang) wherever they appear — some
    # models wrap the message, sometimes after a prose preamble.
    lines = [ln for ln in text.strip().splitlines() if not ln.strip().startswith("```")]
    # Prefer the first line that looks like a commit subject (this skips a chatty
    # "Here's the commit:" preamble); otherwise fall back to the first non-empty line.
    title_idx = next(
        (i for i, ln in enumerate(lines) if _SUBJECT_RE.match(ln.strip())), None
    )
    if title_idx is None:
        title_idx = next((i for i, ln in enumerate(lines) if ln.strip()), None)
    if title_idx is None:
        return None, ""
    title = lines[title_idx].strip()
    body = "\n".join(lines[title_idx + 1:]).strip()
    return title, body


# ------------------------------------------------------------------ providers
def _http_post_json(url: str, payload: dict, timeout: float, headers: dict | None = None) -> dict:
    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(url, data=data, method="POST")
    req.add_header("Content-Type", "application/json")
    for k, v in (headers or {}).items():
        req.add_header(k, v)
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return json.loads(resp.read().decode("utf-8"))


def _call_ollama(ai_cfg, prompt: str) -> str:
    url = ai_cfg.ollama_url.rstrip("/") + "/api/generate"
    payload = {
        "model": ai_cfg.ollama_model,
        "prompt": prompt,
        "stream": False,
        "options": {"temperature": 0.2},
    }
    data = _http_post_json(url, payload, ai_cfg.timeout_sec)
    return (data.get("response") or "").strip()


def _call_cloud(ai_cfg, prompt: str) -> str:
    # For now only Gemini (the chosen provider).
    key = os.environ.get(ai_cfg.api_key_env, "")
    if not key:
        raise RuntimeError(
            f"missing environment variable {ai_cfg.api_key_env} with the API key"
        )
    # Pass the key in a header, NOT the URL query string: a urllib error often
    # stringifies the URL, which would leak the API key into sincrogit.log.
    url = (
        "https://generativelanguage.googleapis.com/v1beta/models/"
        f"{ai_cfg.cloud_model}:generateContent"
    )
    payload = {
        "contents": [{"parts": [{"text": prompt}]}],
        "generationConfig": {"temperature": 0.2, "maxOutputTokens": 256},
    }
    data = _http_post_json(url, payload, ai_cfg.timeout_sec, headers={"x-goog-api-key": key})
    candidates = data.get("candidates") or []
    if not candidates:
        raise RuntimeError(f"response with no candidates: {data}")
    parts = candidates[0].get("content", {}).get("parts", [])
    return "".join(p.get("text", "") for p in parts).strip()
