"""AI commit message generation (hybrid mode).

Order in 'hybrid' mode: Ollama (local) -> Gemini (cloud) -> None (the caller uses
the deterministic fallback). Privacy: the diff content is only sent to the cloud
if `cloud_send_content` is True; otherwise, only `--stat` + names.

Uses only the standard library (urllib) to avoid extra dependencies. The commit
is NEVER blocked by the AI: any failure returns None and the fallback is used.
See §6 of DESIGN.md.
"""

import json
import logging
import os
import urllib.error
import urllib.request

log = logging.getLogger("sincrogit.ai")


def generate_commit_message(ai_cfg, diff_stat: str, diff_text: str):
    """Return (title, body) or None if it couldn't (=> use fallback)."""
    mode = ai_cfg.mode
    if mode == "none":
        return None

    providers = []
    if mode in ("hybrid", "local"):
        providers.append("ollama")
    if mode in ("hybrid", "cloud"):
        providers.append("cloud")

    for provider in providers:
        try:
            if provider == "ollama":
                text = _call_ollama(ai_cfg, _build_prompt(ai_cfg, diff_stat, diff_text, include_content=True))
            else:
                include = bool(ai_cfg.cloud_send_content)
                text = _call_cloud(ai_cfg, _build_prompt(ai_cfg, diff_stat, diff_text, include_content=include))
            title, body = _split_message(text)
            if title:
                log.info("message generated by AI (%s)", provider)
                return title, body
        except Exception as e:  # noqa: BLE001 — any failure falls through to the next
            log.warning("AI (%s) unavailable: %s", provider, e)

    return None


# --------------------------------------------------------------------- prompt
def _build_prompt(ai_cfg, diff_stat: str, diff_text: str, include_content: bool) -> str:
    lang = "Spanish" if ai_cfg.language == "es" else "English"
    body = (
        f"You are an assistant that writes concise git commit messages in {lang}.\n"
        "Based on the following changes, reply ONLY with the commit message:\n"
        "- First line: clear summary of max. 72 characters, no trailing period.\n"
        "- Then, optionally, up to 5 '- ' bullets with the relevant details.\n"
        "Do not add explanations, quotes or code blocks.\n\n"
        "Change summary (git diff --stat):\n"
        f"{diff_stat.strip() or '(no stat)'}\n"
    )
    if include_content and diff_text.strip():
        body += f"\nDiff:\n{diff_text.strip()}\n"
    return body


def _split_message(text: str):
    if not text:
        return None, ""
    cleaned = text.strip()
    # Strip possible code fences that some models add.
    if cleaned.startswith("```"):
        cleaned = cleaned.strip("`").strip()
    lines = [ln for ln in cleaned.splitlines()]
    # First non-empty line = title.
    title = ""
    rest_start = 0
    for i, ln in enumerate(lines):
        if ln.strip():
            title = ln.strip()
            rest_start = i + 1
            break
    body = "\n".join(lines[rest_start:]).strip()
    return title, body


# ------------------------------------------------------------------ providers
def _http_post_json(url: str, payload: dict, timeout: float, headers: dict | None = None) -> dict:
    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(url, data=data, method="POST")
    req.add_header("Content-Type", "application/json")
    for k, v in (headers or {}).items():
        req.add_header(k, v)
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return json.loads(resp.read().decode("utf-8"))


def _call_ollama(ai_cfg, prompt: str) -> str:
    url = ai_cfg.ollama_url.rstrip("/") + "/api/generate"
    payload = {
        "model": ai_cfg.ollama_model,
        "prompt": prompt,
        "stream": False,
        "options": {"temperature": 0.2},
    }
    data = _http_post_json(url, payload, ai_cfg.timeout_sec)
    return (data.get("response") or "").strip()


def _call_cloud(ai_cfg, prompt: str) -> str:
    # For now only Gemini (the chosen provider).
    key = os.environ.get(ai_cfg.api_key_env, "")
    if not key:
        raise RuntimeError(
            f"missing environment variable {ai_cfg.api_key_env} with the API key"
        )
    url = (
        "https://generativelanguage.googleapis.com/v1beta/models/"
        f"{ai_cfg.cloud_model}:generateContent?key={key}"
    )
    payload = {
        "contents": [{"parts": [{"text": prompt}]}],
        "generationConfig": {"temperature": 0.2, "maxOutputTokens": 256},
    }
    data = _http_post_json(url, payload, ai_cfg.timeout_sec)
    candidates = data.get("candidates") or []
    if not candidates:
        raise RuntimeError(f"response with no candidates: {data}")
    parts = candidates[0].get("content", {}).get("parts", [])
    return "".join(p.get("text", "") for p in parts).strip()
